### ISSUE TITLE
Duplicate identifier 'File' with @types/node 20.10.4

### ISSUE THREAD

**Issue by Young-Lord** [msojocs/nt-hook#1]
一个上游的 bug： https://github.com/frida/frida-compile/issues/88

来自原 issue 的具体解决方案：

Downgrading @types/node to 20.9.x can solve the problem.

package.json
```
  "devDependencies": {
    "@types/node": "~20.9"
  }
```

**Comment by msojocs** [comment]
我用的pnpm，好像没遇到

**Comment by Young-Lord** [comment]
我 codespaces 里 npm 就直接炸了，要你觉得问题不大的话 close 掉也行
